# Generated by Django 4.1.13 on 2023-11-04 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='productImageUrl',
        ),
        migrations.AddField(
            model_name='product',
            name='productImage',
            field=models.ImageField(default='shopAPI\\defaultImage\\default-product-image.png', upload_to='pics'),
        ),
    ]
