# Generated by Django 4.1.13 on 2023-11-04 06:06

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(default='', max_length=254, unique=True)),
                ('phoneNumber', models.CharField(max_length=255)),
                ('wishlist', jsonfield.fields.JSONField(default=[])),
                ('transactions', jsonfield.fields.JSONField(default=[])),
            ],
        ),
    ]
