# Generated by Django 4.1.13 on 2023-11-04 06:07

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='transactions',
            field=jsonfield.fields.JSONField(default=[{}]),
        ),
        migrations.AlterField(
            model_name='user',
            name='wishlist',
            field=jsonfield.fields.JSONField(default=[{}]),
        ),
    ]
