# Generated by Django 4.1.13 on 2023-11-04 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_user_transactions_alter_user_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.EmailField(default='', max_length=254),
        ),
    ]
